/*.$file${.::something.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: FortheLoveofTesting.qm
* File:  ${.::something.c}
*
* This code has been generated by QM 4.6.0 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${.::something.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$declare${package1::Class1} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${package1::Class1} .....................................................*/
typedef struct {
/* protected: */
    QActive super;

/* private: */
    QTimeEvt attr1;
} Class1;

/* protected: */
static QState Class1_initial(Class1 * const me, QEvt const * const e);
static QState Class1_state1(Class1 * const me, QEvt const * const e);
static QState Class1_state2(Class1 * const me, QEvt const * const e);
/*.$enddecl${package1::Class1} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 650U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.5.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${package1::Class1} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${package1::Class1} .....................................................*/
/*.${package1::Class1::SM} .................................................*/
static QState Class1_initial(Class1 * const me, QEvt const * const e) {
    /*.${package1::Class1::SM::initial} */
    if (myVariable == 5)
    {
        printf("hello your variable is 5\n");
    }
    return Q_TRAN(&Class1_state1);
}
/*.${package1::Class1::SM::state1} .........................................*/
static QState Class1_state1(Class1 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${package1::Class1::SM::state1} */
        case Q_ENTRY_SIG: {
            printf("Hello\n");
            status_ = Q_HANDLED();
            break;
        }
        /*.${package1::Class1::SM::state1} */
        case Q_EXIT_SIG: {
            myVariable++;
            status_ = Q_HANDLED();
            break;
        }
        /*.${package1::Class1::SM::state1::TRIG1} */
        case TRIG1_SIG: {
            printf("I wonder where this goes\n");
            status_ = Q_TRAN(&Class1_state2);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.${package1::Class1::SM::state2} .........................................*/
static QState Class1_state2(Class1 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${package1::Class1::SM::state2} */
        case Q_ENTRY_SIG: {
            printf("ohno you are now in state two\n");
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.$enddef${package1::Class1} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
